spring:
  datasource:
    url: jdbc:yugabytedb://localhost:5433/ehrbase
    driver-class-name: com.yugabyte.Driver
    hikari:
      maximum-pool-size: 20
      connection-init-sql: 'SET yb_disable_transactional_writes=true'
  jooq:
    sql-dialect: YUGABYTEDB

